"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import
from .icu import get_icu

"""
pdt_locales

All of the included locale classes shipped with pdt.
"""
locales = ...
__locale_caches = ...
__all__ = ['get_icu', 'load_locale']
def load_locale(locale, icu=...):
    """
    Return data of locale
    :param locale:
    :return:
    """
    ...

