"""
This type stub file was generated by pyright.
"""

"""
pdt_locales

All of the included locale classes shipped with pdt.
"""
def icu_object(mapping): # -> Type[_icu]:
    ...

def merge_weekdays(base_wd, icu_wd): # -> list[Unknown]:
    ...

def get_icu(locale): # -> Type[_icu]:
    ...

