"""
This type stub file was generated by pyright.
"""

"""
pdt_locales

All of the included locale classes shipped with pdt.
"""

def icu_object(mapping): ...
def merge_weekdays(base_wd, icu_wd): ...
def get_icu(locale): ...
