# GitHub Action that uses Black to reformat the Python code in an incoming pull request.
# If all Python code in the pull request is complient with Black then this Action does nothing.
# Othewrwise, Black is run and its changes are committed back to the incoming pull request.
# https://github.com/cclauss/autoblack

name: pyright_black_lint_check
on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  pyright:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    name: pyright check ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        id: install-dependencies
        run: |
          python -m pip install --upgrade -r requirements.txt

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Run Pyright
        uses: jakebailey/pyright-action@v1
        with:
          version: "1.1.253"
          warnings: false
          no-comments: ${{ matrix.python-version != '3.x' }}

  black:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    name: black check ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        id: install-dependencies
        run: |
          python -m pip install -U -r requirements.txt

      - name: Run black
        run: python -m black --check --verbose *
